// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package queries

import (
	"context"
)

const countGroups = `-- name: CountGroups :one
SELECT COUNT(*) FROM groups
`

func (q *Queries) CountGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name) VALUES (?) RETURNING id, name, created_at
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, name)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const getAllGroups = `-- name: GetAllGroups :many
SELECT id, name, created_at FROM groups ORDER BY name
`

func (q *Queries) GetAllGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, created_at FROM groups WHERE id = ?
`

func (q *Queries) GetGroupByID(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, name, created_at FROM groups WHERE name = ?
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getGroupLinkCount = `-- name: GetGroupLinkCount :one
SELECT COUNT(*) FROM link_groups WHERE group_id = ?
`

func (q *Queries) GetGroupLinkCount(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getGroupLinkCount, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGroupsPaginated = `-- name: GetGroupsPaginated :many
SELECT id, name, created_at FROM groups ORDER BY name LIMIT ? OFFSET ?
`

type GetGroupsPaginatedParams struct {
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

func (q *Queries) GetGroupsPaginated(ctx context.Context, arg GetGroupsPaginatedParams) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupName = `-- name: UpdateGroupName :exec
UPDATE groups SET name = ? WHERE id = ?
`

type UpdateGroupNameParams struct {
	Name string `db:"name" json:"name"`
	ID   int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupName, arg.Name, arg.ID)
	return err
}
