// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package queries

import (
	"context"
	"database/sql"
	"strings"
)

const addLinkToGroup = `-- name: AddLinkToGroup :exec
INSERT OR IGNORE INTO link_groups (link_id, group_id, position) VALUES (?, ?, ?)
`

type AddLinkToGroupParams struct {
	LinkID   int64         `db:"link_id" json:"link_id"`
	GroupID  int64         `db:"group_id" json:"group_id"`
	Position sql.NullInt64 `db:"position" json:"position"`
}

func (q *Queries) AddLinkToGroup(ctx context.Context, arg AddLinkToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addLinkToGroup, arg.LinkID, arg.GroupID, arg.Position)
	return err
}

const countDeadLinks = `-- name: CountDeadLinks :one
SELECT COUNT(*) FROM shared_links WHERE is_dead = 1
`

func (q *Queries) CountDeadLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeadLinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO shared_links (link, name, protocol, server, port)
VALUES (?, ?, ?, ?, ?)
RETURNING id, link, name, protocol, server, port, is_dead, last_success_at, created_at, updated_at
`

type CreateLinkParams struct {
	Link     string         `db:"link" json:"link"`
	Name     sql.NullString `db:"name" json:"name"`
	Protocol string         `db:"protocol" json:"protocol"`
	Server   sql.NullString `db:"server" json:"server"`
	Port     sql.NullInt64  `db:"port" json:"port"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (SharedLink, error) {
	row := q.db.QueryRowContext(ctx, createLink,
		arg.Link,
		arg.Name,
		arg.Protocol,
		arg.Server,
		arg.Port,
	)
	var i SharedLink
	err := row.Scan(
		&i.ID,
		&i.Link,
		&i.Name,
		&i.Protocol,
		&i.Server,
		&i.Port,
		&i.IsDead,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeadLinks = `-- name: DeleteDeadLinks :execrows
DELETE FROM shared_links WHERE is_dead = 1
`

func (q *Queries) DeleteDeadLinks(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDeadLinks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM shared_links WHERE id = ?
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLink, id)
	return err
}

const deleteLinks = `-- name: DeleteLinks :exec
DELETE FROM shared_links WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) DeleteLinks(ctx context.Context, ids []int64) error {
	query := deleteLinks
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getAllLinkIDs = `-- name: GetAllLinkIDs :many
SELECT id FROM shared_links
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetAllLinkIDsParams struct {
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

func (q *Queries) GetAllLinkIDs(ctx context.Context, arg GetAllLinkIDsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getAllLinkIDs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLinks = `-- name: GetAllLinks :many
SELECT id, link, name, protocol, server, port, is_dead, last_success_at, created_at, updated_at FROM shared_links
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetAllLinksParams struct {
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

func (q *Queries) GetAllLinks(ctx context.Context, arg GetAllLinksParams) ([]SharedLink, error) {
	rows, err := q.db.QueryContext(ctx, getAllLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SharedLink{}
	for rows.Next() {
		var i SharedLink
		if err := rows.Scan(
			&i.ID,
			&i.Link,
			&i.Name,
			&i.Protocol,
			&i.Server,
			&i.Port,
			&i.IsDead,
			&i.LastSuccessAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLinksCount = `-- name: GetAllLinksCount :one
SELECT COUNT(*) FROM shared_links
`

func (q *Queries) GetAllLinksCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAllLinksCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDeadCandidates = `-- name: GetDeadCandidates :many
SELECT id, link FROM shared_links
WHERE is_dead = 0
AND (last_success_at IS NULL OR last_success_at < datetime('now', '-' || CAST(? AS TEXT) || ' days'))
`

type GetDeadCandidatesRow struct {
	ID   int64  `db:"id" json:"id"`
	Link string `db:"link" json:"link"`
}

func (q *Queries) GetDeadCandidates(ctx context.Context, dollar_1 string) ([]GetDeadCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeadCandidates, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDeadCandidatesRow{}
	for rows.Next() {
		var i GetDeadCandidatesRow
		if err := rows.Scan(&i.ID, &i.Link); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeadLinks = `-- name: GetDeadLinks :many
SELECT id, link, name, protocol, server, port, is_dead, last_success_at, created_at, updated_at FROM shared_links WHERE is_dead = 1
`

func (q *Queries) GetDeadLinks(ctx context.Context) ([]SharedLink, error) {
	rows, err := q.db.QueryContext(ctx, getDeadLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SharedLink{}
	for rows.Next() {
		var i SharedLink
		if err := rows.Scan(
			&i.ID,
			&i.Link,
			&i.Name,
			&i.Protocol,
			&i.Server,
			&i.Port,
			&i.IsDead,
			&i.LastSuccessAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT id, link, name, protocol, server, port, is_dead, last_success_at, created_at, updated_at FROM shared_links WHERE id = ?
`

func (q *Queries) GetLinkByID(ctx context.Context, id int64) (SharedLink, error) {
	row := q.db.QueryRowContext(ctx, getLinkByID, id)
	var i SharedLink
	err := row.Scan(
		&i.ID,
		&i.Link,
		&i.Name,
		&i.Protocol,
		&i.Server,
		&i.Port,
		&i.IsDead,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkByURL = `-- name: GetLinkByURL :one
SELECT id, link, name, protocol, server, port, is_dead, last_success_at, created_at, updated_at FROM shared_links WHERE link = ?
`

func (q *Queries) GetLinkByURL(ctx context.Context, link string) (SharedLink, error) {
	row := q.db.QueryRowContext(ctx, getLinkByURL, link)
	var i SharedLink
	err := row.Scan(
		&i.ID,
		&i.Link,
		&i.Name,
		&i.Protocol,
		&i.Server,
		&i.Port,
		&i.IsDead,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkGroups = `-- name: GetLinkGroups :many
SELECT g.id, g.name, g.created_at FROM groups g
JOIN link_groups lg ON g.id = lg.group_id
WHERE lg.link_id = ?
`

func (q *Queries) GetLinkGroups(ctx context.Context, linkID int64) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getLinkGroups, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkIDsForGroup = `-- name: GetLinkIDsForGroup :many
SELECT sl.id FROM shared_links sl
JOIN link_groups lg ON sl.id = lg.link_id
WHERE lg.group_id = ?
ORDER BY lg.position, sl.id
LIMIT ? OFFSET ?
`

type GetLinkIDsForGroupParams struct {
	GroupID int64 `db:"group_id" json:"group_id"`
	Limit   int64 `db:"limit" json:"limit"`
	Offset  int64 `db:"offset" json:"offset"`
}

func (q *Queries) GetLinkIDsForGroup(ctx context.Context, arg GetLinkIDsForGroupParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getLinkIDsForGroup, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinksCountForGroup = `-- name: GetLinksCountForGroup :one
SELECT COUNT(*) FROM link_groups WHERE group_id = ?
`

func (q *Queries) GetLinksCountForGroup(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLinksCountForGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLinksForGroup = `-- name: GetLinksForGroup :many
SELECT sl.id, sl.link, sl.name, sl.protocol, sl.server, sl.port, sl.is_dead, sl.last_success_at, sl.created_at, sl.updated_at FROM shared_links sl
JOIN link_groups lg ON sl.id = lg.link_id
WHERE lg.group_id = ?
ORDER BY lg.position, sl.id
LIMIT ? OFFSET ?
`

type GetLinksForGroupParams struct {
	GroupID int64 `db:"group_id" json:"group_id"`
	Limit   int64 `db:"limit" json:"limit"`
	Offset  int64 `db:"offset" json:"offset"`
}

func (q *Queries) GetLinksForGroup(ctx context.Context, arg GetLinksForGroupParams) ([]SharedLink, error) {
	rows, err := q.db.QueryContext(ctx, getLinksForGroup, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SharedLink{}
	for rows.Next() {
		var i SharedLink
		if err := rows.Scan(
			&i.ID,
			&i.Link,
			&i.Name,
			&i.Protocol,
			&i.Server,
			&i.Port,
			&i.IsDead,
			&i.LastSuccessAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxPositionInGroup = `-- name: GetMaxPositionInGroup :one
SELECT CAST(COALESCE(MAX(position), 0) AS INTEGER) AS max_pos FROM link_groups WHERE group_id = ?
`

func (q *Queries) GetMaxPositionInGroup(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMaxPositionInGroup, groupID)
	var max_pos int64
	err := row.Scan(&max_pos)
	return max_pos, err
}

const isLinkInAnyGroup = `-- name: IsLinkInAnyGroup :one
SELECT EXISTS(SELECT 1 FROM link_groups WHERE link_id = ?) AS in_group
`

func (q *Queries) IsLinkInAnyGroup(ctx context.Context, linkID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, isLinkInAnyGroup, linkID)
	var in_group int64
	err := row.Scan(&in_group)
	return in_group, err
}

const linkExists = `-- name: LinkExists :one
SELECT EXISTS(SELECT 1 FROM shared_links WHERE link = ?) AS link_exists
`

func (q *Queries) LinkExists(ctx context.Context, link string) (int64, error) {
	row := q.db.QueryRowContext(ctx, linkExists, link)
	var link_exists int64
	err := row.Scan(&link_exists)
	return link_exists, err
}

const markLinkAlive = `-- name: MarkLinkAlive :exec
UPDATE shared_links
SET is_dead = 0, last_success_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkLinkAlive(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markLinkAlive, id)
	return err
}

const markLinkDead = `-- name: MarkLinkDead :exec
UPDATE shared_links
SET is_dead = 1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkLinkDead(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markLinkDead, id)
	return err
}

const moveLinkToGroup = `-- name: MoveLinkToGroup :exec
INSERT OR REPLACE INTO link_groups (link_id, group_id, position) VALUES (?, ?, ?)
`

type MoveLinkToGroupParams struct {
	LinkID   int64         `db:"link_id" json:"link_id"`
	GroupID  int64         `db:"group_id" json:"group_id"`
	Position sql.NullInt64 `db:"position" json:"position"`
}

func (q *Queries) MoveLinkToGroup(ctx context.Context, arg MoveLinkToGroupParams) error {
	_, err := q.db.ExecContext(ctx, moveLinkToGroup, arg.LinkID, arg.GroupID, arg.Position)
	return err
}

const removeLinkFromGroup = `-- name: RemoveLinkFromGroup :exec
DELETE FROM link_groups WHERE link_id = ? AND group_id = ?
`

type RemoveLinkFromGroupParams struct {
	LinkID  int64 `db:"link_id" json:"link_id"`
	GroupID int64 `db:"group_id" json:"group_id"`
}

func (q *Queries) RemoveLinkFromGroup(ctx context.Context, arg RemoveLinkFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removeLinkFromGroup, arg.LinkID, arg.GroupID)
	return err
}

const removeLinksFromGroup = `-- name: RemoveLinksFromGroup :exec
DELETE FROM link_groups WHERE link_id IN (/*SLICE:link_ids*/?) AND group_id = ?
`

type RemoveLinksFromGroupParams struct {
	LinkIds []int64 `db:"link_ids" json:"link_ids"`
	GroupID int64   `db:"group_id" json:"group_id"`
}

func (q *Queries) RemoveLinksFromGroup(ctx context.Context, arg RemoveLinksFromGroupParams) error {
	query := removeLinksFromGroup
	var queryParams []interface{}
	if len(arg.LinkIds) > 0 {
		for _, v := range arg.LinkIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:link_ids*/?", strings.Repeat(",?", len(arg.LinkIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:link_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.GroupID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const searchLinks = `-- name: SearchLinks :many
SELECT id, link, name, protocol, server, port, is_dead, last_success_at, created_at, updated_at FROM shared_links
WHERE name LIKE ? OR link LIKE ? OR server LIKE ?
ORDER BY created_at DESC
LIMIT ?
`

type SearchLinksParams struct {
	Name   sql.NullString `db:"name" json:"name"`
	Link   string         `db:"link" json:"link"`
	Server sql.NullString `db:"server" json:"server"`
	Limit  int64          `db:"limit" json:"limit"`
}

func (q *Queries) SearchLinks(ctx context.Context, arg SearchLinksParams) ([]SharedLink, error) {
	rows, err := q.db.QueryContext(ctx, searchLinks,
		arg.Name,
		arg.Link,
		arg.Server,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SharedLink{}
	for rows.Next() {
		var i SharedLink
		if err := rows.Scan(
			&i.ID,
			&i.Link,
			&i.Name,
			&i.Protocol,
			&i.Server,
			&i.Port,
			&i.IsDead,
			&i.LastSuccessAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastSuccess = `-- name: UpdateLastSuccess :exec
UPDATE shared_links
SET last_success_at = CURRENT_TIMESTAMP, is_dead = 0, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateLastSuccess(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateLastSuccess, id)
	return err
}

const updateLink = `-- name: UpdateLink :exec
UPDATE shared_links
SET name = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateLinkParams struct {
	Name sql.NullString `db:"name" json:"name"`
	ID   int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) error {
	_, err := q.db.ExecContext(ctx, updateLink, arg.Name, arg.ID)
	return err
}
