// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: measurements.sql

package queries

import (
	"context"
	"database/sql"
)

const countHealthchecks = `-- name: CountHealthchecks :one
SELECT COUNT(*) FROM healthcheck_measurements
`

func (q *Queries) CountHealthchecks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHealthchecks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPingMeasurements = `-- name: CountPingMeasurements :one
SELECT COUNT(*) FROM ping_measurements
`

func (q *Queries) CountPingMeasurements(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPingMeasurements)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSpeedMeasurements = `-- name: CountSpeedMeasurements :one
SELECT COUNT(*) FROM speed_measurements
`

func (q *Queries) CountSpeedMeasurements(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpeedMeasurements)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getHealthcheckHistory = `-- name: GetHealthcheckHistory :many
SELECT id, link_id, success, error_message, measured_at FROM healthcheck_measurements
WHERE link_id = ?
ORDER BY measured_at DESC
LIMIT ?
`

type GetHealthcheckHistoryParams struct {
	LinkID int64 `db:"link_id" json:"link_id"`
	Limit  int64 `db:"limit" json:"limit"`
}

func (q *Queries) GetHealthcheckHistory(ctx context.Context, arg GetHealthcheckHistoryParams) ([]HealthcheckMeasurement, error) {
	rows, err := q.db.QueryContext(ctx, getHealthcheckHistory, arg.LinkID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HealthcheckMeasurement{}
	for rows.Next() {
		var i HealthcheckMeasurement
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.Success,
			&i.ErrorMessage,
			&i.MeasuredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHealthcheckStats = `-- name: GetHealthcheckStats :one
SELECT
    COUNT(*) AS total,
    SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) AS successful,
    SUM(CASE WHEN success = 0 THEN 1 ELSE 0 END) AS failed
FROM healthcheck_measurements
WHERE link_id = ?
AND measured_at > datetime('now', '-' || ? || ' days')
`

type GetHealthcheckStatsParams struct {
	LinkID  int64          `db:"link_id" json:"link_id"`
	Column2 sql.NullString `db:"column_2" json:"column_2"`
}

type GetHealthcheckStatsRow struct {
	Total      int64           `db:"total" json:"total"`
	Successful sql.NullFloat64 `db:"successful" json:"successful"`
	Failed     sql.NullFloat64 `db:"failed" json:"failed"`
}

func (q *Queries) GetHealthcheckStats(ctx context.Context, arg GetHealthcheckStatsParams) (GetHealthcheckStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getHealthcheckStats, arg.LinkID, arg.Column2)
	var i GetHealthcheckStatsRow
	err := row.Scan(&i.Total, &i.Successful, &i.Failed)
	return i, err
}

const getLatestHealthcheck = `-- name: GetLatestHealthcheck :one
SELECT id, link_id, success, error_message, measured_at FROM healthcheck_measurements
WHERE link_id = ?
ORDER BY measured_at DESC
LIMIT 1
`

func (q *Queries) GetLatestHealthcheck(ctx context.Context, linkID int64) (HealthcheckMeasurement, error) {
	row := q.db.QueryRowContext(ctx, getLatestHealthcheck, linkID)
	var i HealthcheckMeasurement
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.Success,
		&i.ErrorMessage,
		&i.MeasuredAt,
	)
	return i, err
}

const getLatestPing = `-- name: GetLatestPing :one
SELECT id, link_id, latency_ms, success, error_message, measured_at FROM ping_measurements
WHERE link_id = ?
ORDER BY measured_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPing(ctx context.Context, linkID int64) (PingMeasurement, error) {
	row := q.db.QueryRowContext(ctx, getLatestPing, linkID)
	var i PingMeasurement
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.LatencyMs,
		&i.Success,
		&i.ErrorMessage,
		&i.MeasuredAt,
	)
	return i, err
}

const getLatestSpeed = `-- name: GetLatestSpeed :one
SELECT id, link_id, download_speed_bps, upload_speed_bps, success, error_message, measured_at FROM speed_measurements
WHERE link_id = ?
ORDER BY measured_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSpeed(ctx context.Context, linkID int64) (SpeedMeasurement, error) {
	row := q.db.QueryRowContext(ctx, getLatestSpeed, linkID)
	var i SpeedMeasurement
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.DownloadSpeedBps,
		&i.UploadSpeedBps,
		&i.Success,
		&i.ErrorMessage,
		&i.MeasuredAt,
	)
	return i, err
}

const getPingHistory = `-- name: GetPingHistory :many
SELECT id, link_id, latency_ms, success, error_message, measured_at FROM ping_measurements
WHERE link_id = ?
ORDER BY measured_at DESC
LIMIT ?
`

type GetPingHistoryParams struct {
	LinkID int64 `db:"link_id" json:"link_id"`
	Limit  int64 `db:"limit" json:"limit"`
}

func (q *Queries) GetPingHistory(ctx context.Context, arg GetPingHistoryParams) ([]PingMeasurement, error) {
	rows, err := q.db.QueryContext(ctx, getPingHistory, arg.LinkID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PingMeasurement{}
	for rows.Next() {
		var i PingMeasurement
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.LatencyMs,
			&i.Success,
			&i.ErrorMessage,
			&i.MeasuredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPingStats = `-- name: GetPingStats :one
SELECT
    COUNT(*) AS total,
    AVG(CASE WHEN success = 1 THEN latency_ms END) AS avg_latency,
    MIN(CASE WHEN success = 1 THEN latency_ms END) AS min_latency,
    MAX(CASE WHEN success = 1 THEN latency_ms END) AS max_latency
FROM ping_measurements
WHERE link_id = ?
AND measured_at > datetime('now', '-' || ? || ' days')
`

type GetPingStatsParams struct {
	LinkID  int64          `db:"link_id" json:"link_id"`
	Column2 sql.NullString `db:"column_2" json:"column_2"`
}

type GetPingStatsRow struct {
	Total      int64           `db:"total" json:"total"`
	AvgLatency sql.NullFloat64 `db:"avg_latency" json:"avg_latency"`
	MinLatency interface{}     `db:"min_latency" json:"min_latency"`
	MaxLatency interface{}     `db:"max_latency" json:"max_latency"`
}

func (q *Queries) GetPingStats(ctx context.Context, arg GetPingStatsParams) (GetPingStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getPingStats, arg.LinkID, arg.Column2)
	var i GetPingStatsRow
	err := row.Scan(
		&i.Total,
		&i.AvgLatency,
		&i.MinLatency,
		&i.MaxLatency,
	)
	return i, err
}

const getSpeedHistory = `-- name: GetSpeedHistory :many
SELECT id, link_id, download_speed_bps, upload_speed_bps, success, error_message, measured_at FROM speed_measurements
WHERE link_id = ?
ORDER BY measured_at DESC
LIMIT ?
`

type GetSpeedHistoryParams struct {
	LinkID int64 `db:"link_id" json:"link_id"`
	Limit  int64 `db:"limit" json:"limit"`
}

func (q *Queries) GetSpeedHistory(ctx context.Context, arg GetSpeedHistoryParams) ([]SpeedMeasurement, error) {
	rows, err := q.db.QueryContext(ctx, getSpeedHistory, arg.LinkID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpeedMeasurement{}
	for rows.Next() {
		var i SpeedMeasurement
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.DownloadSpeedBps,
			&i.UploadSpeedBps,
			&i.Success,
			&i.ErrorMessage,
			&i.MeasuredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpeedStats = `-- name: GetSpeedStats :one
SELECT
    COUNT(*) AS total,
    AVG(CASE WHEN success = 1 THEN download_speed_bps END) AS avg_download,
    MAX(CASE WHEN success = 1 THEN download_speed_bps END) AS max_download,
    AVG(CASE WHEN success = 1 THEN upload_speed_bps END) AS avg_upload
FROM speed_measurements
WHERE link_id = ?
AND measured_at > datetime('now', '-' || ? || ' days')
`

type GetSpeedStatsParams struct {
	LinkID  int64          `db:"link_id" json:"link_id"`
	Column2 sql.NullString `db:"column_2" json:"column_2"`
}

type GetSpeedStatsRow struct {
	Total       int64           `db:"total" json:"total"`
	AvgDownload sql.NullFloat64 `db:"avg_download" json:"avg_download"`
	MaxDownload interface{}     `db:"max_download" json:"max_download"`
	AvgUpload   sql.NullFloat64 `db:"avg_upload" json:"avg_upload"`
}

func (q *Queries) GetSpeedStats(ctx context.Context, arg GetSpeedStatsParams) (GetSpeedStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getSpeedStats, arg.LinkID, arg.Column2)
	var i GetSpeedStatsRow
	err := row.Scan(
		&i.Total,
		&i.AvgDownload,
		&i.MaxDownload,
		&i.AvgUpload,
	)
	return i, err
}

const insertHealthcheck = `-- name: InsertHealthcheck :exec

INSERT INTO healthcheck_measurements (link_id, success, error_message)
VALUES (?, ?, ?)
`

type InsertHealthcheckParams struct {
	LinkID       int64          `db:"link_id" json:"link_id"`
	Success      int64          `db:"success" json:"success"`
	ErrorMessage sql.NullString `db:"error_message" json:"error_message"`
}

// Healthcheck measurements
func (q *Queries) InsertHealthcheck(ctx context.Context, arg InsertHealthcheckParams) error {
	_, err := q.db.ExecContext(ctx, insertHealthcheck, arg.LinkID, arg.Success, arg.ErrorMessage)
	return err
}

const insertPingMeasurement = `-- name: InsertPingMeasurement :exec

INSERT INTO ping_measurements (link_id, latency_ms, success, error_message)
VALUES (?, ?, ?, ?)
`

type InsertPingMeasurementParams struct {
	LinkID       int64          `db:"link_id" json:"link_id"`
	LatencyMs    sql.NullInt64  `db:"latency_ms" json:"latency_ms"`
	Success      int64          `db:"success" json:"success"`
	ErrorMessage sql.NullString `db:"error_message" json:"error_message"`
}

// Ping measurements
func (q *Queries) InsertPingMeasurement(ctx context.Context, arg InsertPingMeasurementParams) error {
	_, err := q.db.ExecContext(ctx, insertPingMeasurement,
		arg.LinkID,
		arg.LatencyMs,
		arg.Success,
		arg.ErrorMessage,
	)
	return err
}

const insertSpeedMeasurement = `-- name: InsertSpeedMeasurement :exec

INSERT INTO speed_measurements (link_id, download_speed_bps, upload_speed_bps, success, error_message)
VALUES (?, ?, ?, ?, ?)
`

type InsertSpeedMeasurementParams struct {
	LinkID           int64          `db:"link_id" json:"link_id"`
	DownloadSpeedBps sql.NullInt64  `db:"download_speed_bps" json:"download_speed_bps"`
	UploadSpeedBps   sql.NullInt64  `db:"upload_speed_bps" json:"upload_speed_bps"`
	Success          int64          `db:"success" json:"success"`
	ErrorMessage     sql.NullString `db:"error_message" json:"error_message"`
}

// Speed measurements
func (q *Queries) InsertSpeedMeasurement(ctx context.Context, arg InsertSpeedMeasurementParams) error {
	_, err := q.db.ExecContext(ctx, insertSpeedMeasurement,
		arg.LinkID,
		arg.DownloadSpeedBps,
		arg.UploadSpeedBps,
		arg.Success,
		arg.ErrorMessage,
	)
	return err
}

const purgeOldHealthchecks = `-- name: PurgeOldHealthchecks :execrows
DELETE FROM healthcheck_measurements
WHERE id IN (
    SELECT id FROM healthcheck_measurements
    ORDER BY measured_at DESC
    LIMIT -1 OFFSET ?
)
`

func (q *Queries) PurgeOldHealthchecks(ctx context.Context, offset int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeOldHealthchecks, offset)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeOldPingMeasurements = `-- name: PurgeOldPingMeasurements :execrows
DELETE FROM ping_measurements
WHERE id IN (
    SELECT id FROM ping_measurements
    ORDER BY measured_at DESC
    LIMIT -1 OFFSET ?
)
`

func (q *Queries) PurgeOldPingMeasurements(ctx context.Context, offset int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeOldPingMeasurements, offset)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeOldSpeedMeasurements = `-- name: PurgeOldSpeedMeasurements :execrows
DELETE FROM speed_measurements
WHERE id IN (
    SELECT id FROM speed_measurements
    ORDER BY measured_at DESC
    LIMIT -1 OFFSET ?
)
`

func (q *Queries) PurgeOldSpeedMeasurements(ctx context.Context, offset int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeOldSpeedMeasurements, offset)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
