// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Group struct {
	ID        int64        `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

type HealthcheckMeasurement struct {
	ID           int64          `db:"id" json:"id"`
	LinkID       int64          `db:"link_id" json:"link_id"`
	Success      int64          `db:"success" json:"success"`
	ErrorMessage sql.NullString `db:"error_message" json:"error_message"`
	MeasuredAt   sql.NullTime   `db:"measured_at" json:"measured_at"`
}

type LinkGroup struct {
	LinkID   int64         `db:"link_id" json:"link_id"`
	GroupID  int64         `db:"group_id" json:"group_id"`
	Position sql.NullInt64 `db:"position" json:"position"`
}

type LinksFt struct {
	Name   string `db:"name" json:"name"`
	Server string `db:"server" json:"server"`
	Link   string `db:"link" json:"link"`
}

type PingMeasurement struct {
	ID           int64          `db:"id" json:"id"`
	LinkID       int64          `db:"link_id" json:"link_id"`
	LatencyMs    sql.NullInt64  `db:"latency_ms" json:"latency_ms"`
	Success      int64          `db:"success" json:"success"`
	ErrorMessage sql.NullString `db:"error_message" json:"error_message"`
	MeasuredAt   sql.NullTime   `db:"measured_at" json:"measured_at"`
}

type SchemaMigration struct {
	Version   int64        `db:"version" json:"version"`
	AppliedAt sql.NullTime `db:"applied_at" json:"applied_at"`
}

type Setting struct {
	Key   string `db:"key" json:"key"`
	Value string `db:"value" json:"value"`
}

type SharedLink struct {
	ID            int64          `db:"id" json:"id"`
	Link          string         `db:"link" json:"link"`
	Name          sql.NullString `db:"name" json:"name"`
	Protocol      string         `db:"protocol" json:"protocol"`
	Server        sql.NullString `db:"server" json:"server"`
	Port          sql.NullInt64  `db:"port" json:"port"`
	IsDead        sql.NullInt64  `db:"is_dead" json:"is_dead"`
	LastSuccessAt sql.NullTime   `db:"last_success_at" json:"last_success_at"`
	CreatedAt     sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt     sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type SpeedMeasurement struct {
	ID               int64          `db:"id" json:"id"`
	LinkID           int64          `db:"link_id" json:"link_id"`
	DownloadSpeedBps sql.NullInt64  `db:"download_speed_bps" json:"download_speed_bps"`
	UploadSpeedBps   sql.NullInt64  `db:"upload_speed_bps" json:"upload_speed_bps"`
	Success          int64          `db:"success" json:"success"`
	ErrorMessage     sql.NullString `db:"error_message" json:"error_message"`
	MeasuredAt       sql.NullTime   `db:"measured_at" json:"measured_at"`
}

type Subscription struct {
	ID                  int64          `db:"id" json:"id"`
	Url                 string         `db:"url" json:"url"`
	Name                sql.NullString `db:"name" json:"name"`
	Enabled             sql.NullInt64  `db:"enabled" json:"enabled"`
	LastUpdatedAt       sql.NullTime   `db:"last_updated_at" json:"last_updated_at"`
	LastError           sql.NullString `db:"last_error" json:"last_error"`
	RequestCount        sql.NullInt64  `db:"request_count" json:"request_count"`
	RequestCountResetAt sql.NullTime   `db:"request_count_reset_at" json:"request_count_reset_at"`
	CreatedAt           sql.NullTime   `db:"created_at" json:"created_at"`
}
