// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateProxy(arg1:number):Promise<void>;

export function AddProxies(arg1:Array<string>,arg2:any):Promise<number>;

export function AddProxy(arg1:string,arg2:any):Promise<void>;

export function AddSubscription(arg1:string,arg2:string):Promise<void>;

export function ClearSystemProxy():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateGroup(arg1:string):Promise<main.Group>;

export function DeactivateProxy():Promise<void>;

export function DeleteDeadProxies():Promise<number>;

export function DeleteGroup(arg1:number):Promise<void>;

export function DeleteProxies(arg1:Array<number>):Promise<void>;

export function DeleteProxy(arg1:number):Promise<void>;

export function DeleteSubscription(arg1:number):Promise<void>;

export function DisableTun():Promise<void>;

export function EnableTun(arg1:number):Promise<void>;

export function GetActiveProxy():Promise<main.ActiveProxyInfo>;

export function GetClipboard():Promise<string>;

export function GetDeadProxyCount():Promise<number>;

export function GetGroupCount():Promise<number>;

export function GetGroups():Promise<Array<main.Group>>;

export function GetGroupsPaginated(arg1:number,arg2:number):Promise<Array<main.Group>>;

export function GetHealthStats(arg1:number):Promise<main.HealthStats>;

export function GetListenAddress():Promise<string>;

export function GetMeasurementCounts():Promise<main.MeasurementCounts>;

export function GetPingHistory(arg1:number,arg2:number):Promise<Array<main.PingPoint>>;

export function GetProxies(arg1:number,arg2:number,arg3:number):Promise<Array<main.ProxyInfo>>;

export function GetProxyCount(arg1:number):Promise<number>;

export function GetProxyDetails(arg1:number):Promise<main.ProxyDetails>;

export function GetProxyIDs(arg1:number,arg2:number,arg3:number):Promise<Array<number>>;

export function GetProxyStats(arg1:number):Promise<main.ProxyStats>;

export function GetSettings():Promise<main.Settings>;

export function GetSpeedHistory(arg1:number,arg2:number):Promise<Array<main.SpeedPoint>>;

export function GetSubscriptions():Promise<Array<main.Subscription>>;

export function GetTunStatus():Promise<main.TunStatus>;

export function IsSystemProxySet():Promise<boolean>;

export function MoveProxiesToGroup(arg1:Array<number>,arg2:number):Promise<void>;

export function MoveToGroup(arg1:number,arg2:number):Promise<void>;

export function ParseClipboard():Promise<main.ClipboardContent>;

export function RenameGroup(arg1:number,arg2:string):Promise<void>;

export function SearchGroups(arg1:string,arg2:number,arg3:number):Promise<main.SearchGroupsResult>;

export function SearchProxies(arg1:number,arg2:string,arg3:number,arg4:number):Promise<main.SearchProxiesResult>;

export function SetListenAddress(arg1:string):Promise<void>;

export function SetSystemProxy():Promise<void>;

export function ToggleSubscription(arg1:number,arg2:boolean):Promise<void>;

export function UpdateSettings(arg1:main.Settings):Promise<void>;

export function UpdateSubscription(arg1:number):Promise<void>;
