// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateProxy(arg1) {
  return window['go']['main']['App']['ActivateProxy'](arg1);
}

export function AddProxies(arg1, arg2) {
  return window['go']['main']['App']['AddProxies'](arg1, arg2);
}

export function AddProxy(arg1, arg2) {
  return window['go']['main']['App']['AddProxy'](arg1, arg2);
}

export function AddSubscription(arg1, arg2) {
  return window['go']['main']['App']['AddSubscription'](arg1, arg2);
}

export function ClearSystemProxy() {
  return window['go']['main']['App']['ClearSystemProxy']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function DeactivateProxy() {
  return window['go']['main']['App']['DeactivateProxy']();
}

export function DeleteDeadProxies() {
  return window['go']['main']['App']['DeleteDeadProxies']();
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteProxies(arg1) {
  return window['go']['main']['App']['DeleteProxies'](arg1);
}

export function DeleteProxy(arg1) {
  return window['go']['main']['App']['DeleteProxy'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function DisableTun() {
  return window['go']['main']['App']['DisableTun']();
}

export function EnableTun(arg1) {
  return window['go']['main']['App']['EnableTun'](arg1);
}

export function GetActiveProxy() {
  return window['go']['main']['App']['GetActiveProxy']();
}

export function GetClipboard() {
  return window['go']['main']['App']['GetClipboard']();
}

export function GetDeadProxyCount() {
  return window['go']['main']['App']['GetDeadProxyCount']();
}

export function GetGroupCount() {
  return window['go']['main']['App']['GetGroupCount']();
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetGroupsPaginated(arg1, arg2) {
  return window['go']['main']['App']['GetGroupsPaginated'](arg1, arg2);
}

export function GetHealthStats(arg1) {
  return window['go']['main']['App']['GetHealthStats'](arg1);
}

export function GetListenAddress() {
  return window['go']['main']['App']['GetListenAddress']();
}

export function GetMeasurementCounts() {
  return window['go']['main']['App']['GetMeasurementCounts']();
}

export function GetPingHistory(arg1, arg2) {
  return window['go']['main']['App']['GetPingHistory'](arg1, arg2);
}

export function GetProxies(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProxies'](arg1, arg2, arg3);
}

export function GetProxyCount(arg1) {
  return window['go']['main']['App']['GetProxyCount'](arg1);
}

export function GetProxyDetails(arg1) {
  return window['go']['main']['App']['GetProxyDetails'](arg1);
}

export function GetProxyIDs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProxyIDs'](arg1, arg2, arg3);
}

export function GetProxyStats(arg1) {
  return window['go']['main']['App']['GetProxyStats'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSpeedHistory(arg1, arg2) {
  return window['go']['main']['App']['GetSpeedHistory'](arg1, arg2);
}

export function GetSubscriptions() {
  return window['go']['main']['App']['GetSubscriptions']();
}

export function GetTunStatus() {
  return window['go']['main']['App']['GetTunStatus']();
}

export function IsSystemProxySet() {
  return window['go']['main']['App']['IsSystemProxySet']();
}

export function MoveProxiesToGroup(arg1, arg2) {
  return window['go']['main']['App']['MoveProxiesToGroup'](arg1, arg2);
}

export function MoveToGroup(arg1, arg2) {
  return window['go']['main']['App']['MoveToGroup'](arg1, arg2);
}

export function ParseClipboard() {
  return window['go']['main']['App']['ParseClipboard']();
}

export function RenameGroup(arg1, arg2) {
  return window['go']['main']['App']['RenameGroup'](arg1, arg2);
}

export function SearchGroups(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchGroups'](arg1, arg2, arg3);
}

export function SearchProxies(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchProxies'](arg1, arg2, arg3, arg4);
}

export function SetListenAddress(arg1) {
  return window['go']['main']['App']['SetListenAddress'](arg1);
}

export function SetSystemProxy() {
  return window['go']['main']['App']['SetSystemProxy']();
}

export function ToggleSubscription(arg1, arg2) {
  return window['go']['main']['App']['ToggleSubscription'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateSubscription(arg1) {
  return window['go']['main']['App']['UpdateSubscription'](arg1);
}
